version: '2'

services:
  icecast:
    build: icecast
    environment:
        SERVICE_FQDN_STREAM_8000:


  # Add your host volumen in path/to/... or add your own volume below
  mpd:
    build: mpd
    depends_on:
      - icecast
    # environment:
    #     SERVICE_FQDN_STREAM_6600: /mpd
    volumes:
      - ./mpd_music:/var/lib/mpd/music
      - ./mpd_playlists:/var/lib/mpd/playlists
      - ./mpd_database:/var/lib/mpd/database

  sima:
    build: sima
    depends_on:
      - mpd

  ympd:
    build: ympd
    depends_on:
      - mpd
    environment:
        SERVICE_FQDN_STREAM_8080: /ymdp
